
export const hurb = {


    SITE: 'https://www.hurb.com/',
    ENTRAR: ':nth-child(3) > .h-1j9fxlj > :nth-child(3) > :nth-child(1) > div > .hrc-Grvo8',
    CRIARCONTA: '.hrc-CXFlO > .hrc-21pPo',
    PREENCHERNOME:'#firstName',
    NOME: "Dovahkiin",
    PREENCHERSOBRENOME: '#lastName',
    SOBRENOME: "Jarl",
    PREENCHEREMAIL: '#email',
    EMAIL:"jarldovahkiin55@gmail.com",
    PREENCHERSENHA: '#password',
    SENHA: "12345Aa$$12345Aa$$",
    BOTAOENTRAR: "form > .hrc-Grvo8",
    COOKIE:'#CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll',
    CONFIRMARSENHA:'#passwordConfirmation',
    SELECTPAIS:'#country',
    PAIS: "Brasil",
    SELECTESTADO: '#stateProvince',
    ESTADO: "São Paulo",      
    SELECTBOX:'#newsOptIn',
    BOTAOCRIAR: 'form > .hrc-2odzf',
    PERFIL: '[style="display: block;"] > div > .hrc-Grvo8 > .hrc-1ul7R',
    INFOPESSOAIS: '[href="https://www.hurb.com/br/account/me"] > .hrc-2rGYR > .hrc-21pPo',
    ANIVERSARIO: '#birthday',
    DATA: '16/01/1998', 
    GENERO: ':nth-child(2) > .hrc-RyftB > .hrc-2qRho',
    PREENCHERTELEFONE: '#homePhone',
    TELEFONE: '1120425200',
    PREENCHERCELULAR: '#mobilePhone',
    CELULAR: '11920425200',
    SELECTBOX2: '#whatsapp',
    SELECTBOX3: '#news',
    BOTAOSALVAR: '.UserForm_SubmitBox__T1Oxv > .hrc-2odzf',
    MINHASVIAGENS: '[href="https://www.hurb.com/br/account/orders"] > .NavItemText_Wrapper__3W5HU > .hrc-258xz',
    STATUSPAGAMENTO: '.OrdersFilter_Wrapper__2BBWx > div > .hrc-Grvo8',
    FILTRO1: ':nth-child(1) > .hrc-1xdW6 > .hrc-2Synk',
    FILTRO2: ':nth-child(4) > .hrc-1xdW6 > .hrc-2Synk',
    FILTRO3: ':nth-child(6) > .hrc-1xdW6 > .hrc-2Synk',
    APLICAR: '.OrdersFilter_Footer__37_BR > .hrc-1JJ4p',
    MEUSCREDITOS: '[href="https://www.hurb.com/br/account/credits"] > .NavItemText_Wrapper__3W5HU > .hrc-258xz',
    SOLICITACOES: '[href="https://www.hurb.com/br/account/requests"]',
    CONVIDARAMIGO: '[href="https://www.hurb.com/br/account/member"] > .NavItemText_Wrapper__3W5HU > .hrc-258xz',
    Botao: '.hrc-GLtuU > .hrc-Grvo8 > .hrc-1ul7R',
    SAIR: ':nth-child(3) > .hrc-32_pR > .hrc-C_E4e > .hrc-21pPo',
}